name: supabase_auth_bloc
description: Dart package which manages the flutter_supabase_auth_bloc domain.
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  meta: ^1.8.0
  equatable: ^2.0.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  supabase_auth_repo:
    path: ../flutter_supabase_auth_repo

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.7